
name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Something
        run: |
          echo "Hello World"
          echo "$(pwd)"
